### ISSUE TITLE
Feature requests for seek-to.lua

### ISSUE THREAD

**Issue by KonoVitoDa** [Sneakpeakcss/mpv-config-seek-to#1]
- Paste timestamp while seeker is hidden, like the original fork by @dexeonify does
- Make the ```paste_timestamp``` function to accept timestamps formatted as ```HH.MM.SS.mmm``` (dots in place of colons), so it's easier to copy-paste timestamps taken from screenshots filenames
- *For files longer than an hour, keep the initial cursor position in the minutes field
- *Act like MPC-HC and start the seeker with the current playback time set

The ones I marked with * are kind of personal preferences, so they can be treated with lower priority. but the first two appears to be real improvements.

**Comment by Sneakpeakcss** [comment]
> * Paste timestamp while seeker is hidden, like the original fork by @dexeonify does

You can now bind it as `script-message paste-timestamp`

> * Make the `paste_timestamp` function to accept timestamps formatted as `HH.MM.SS.mmm` (dots in place of colons), so it's easier to copy-paste timestamps taken from screenshots filenames

This one is a bit more tricky, since it was always assumed that only milliseconds are seperated by dots, but unless i missed something, it should work now:

> For best results use at least 3 digits for milliseconds (.000) or a full
> timestamp HH.MM.SS.sss (00.00.00.1):
> 
> 00.11.31.527
> 11.11.11.2
> 1.23.11.5
> 00.61.611
> 11.30.527
> 11.30.000
> 61.61 (this will be treated as 1m1s610ms)
___

>  * *For files longer than an hour, keep the initial cursor position in the minutes field
> 
>  * *Act like MPC-HC and start the seeker with the current playback time set

Most of the code for this is already there. One of the issues with the latter is that it interferes too much with the different modes that you toggle with `-` `+` `=` / `KP_ - + *` keys. It's far more useful in MPC-HC because you can copy the timestamp straight from the box.

You can edit `set_active()` function to achieve both:

```diff
 function set_active()
     if not mp.get_property("seekable") then return end
+    local current_time = mp.get_property_osd("time-pos/full") or "00:00:00.000"
+    local timestamp_digits = {current_time:match("(%d)(%d):(%d)(%d):(%d)(%d)%.(%d)(%d)(%d)")}
+    for i = 1, 9 do
+        history[#history][i] = tonumber(timestamp_digits[i])
+    end
     -- find duration of the video and set cursor position accordingly
     local duration = mp.get_property_number("duration")
     if duration ~= nil then
-        for i = 1, 9 do
-            if duration > time_scale[i] then
-                cursor_position = i
-                break
+        if duration > time_scale[2] then
+            cursor_position = 3  -- Starting digit selection for files longer than 1h
+        else
+            for i = 1, 9 do
+                if duration > time_scale[i] then
+                    cursor_position = i
+                    break
+                end
             end
         end
    end
    for key, func in pairs(key_mappings) do
        mp.add_forced_key_binding(key, "seek-to-"..key, func, {repeatable=true})
    end
    show_seeker()
    active = true
    blink_timer = mp.add_periodic_timer(1 / blink_rate, show_seeker)
end
```

**Comment by KonoVitoDa** [comment]
Wow, this was fast. Thank you very much, king! 😊

> For best results use at least 3 digits for milliseconds (.000)

No problem, I always use 3 digits for it!

> It's far more useful in 

You're right, I think it's more of an aesthetic preference. The only real advantage I can think of is that it would be easier to take advantage of the already set values ​​if I wanted to seek to a nearby region.

Well, I'll run the tests and try to make the changes you suggested. If I find anything wrong, I'll let you know. Once again, thank you very much!

**EDIT:** Everything is working perfectly so far!
